# -*- coding: utf-8 -*-
"""keras_to_tensorflowjs

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gY-puOIH1RnluEGekY4sSrhW9FRteyqJ
"""



from google.colab import drive
drive.mount('/content/drive')

!pip install tensorflowjs

import tensorflow as tf
import tensorflowjs as tfjs

new_model = tf.keras.models.load_model("/content/drive/MyDrive/K-food-model/n_.h5")

tfjs.converters.save_keras_model(new_model, "/content/drive/MyDrive/K-food-model/tfjs_n_.h5")

